### ISSUE TITLE
Takeover error

### ISSUE THREAD

**Issue by casportal** [edoardottt/takeover#2]
I found takeover finder v0.2 and have been playing around with it, however when I run the (python3 takeover.py -l domains.txt -v) or (python3 takeover.py -d google.com -v) command I get an error which I added below as well as the line 303 of code from the takeover.py file. I'm not sure why the string is invalid and if you have come across this problem before and have a solution. Any help would be greatly appreciated. 

go version go1.22.5 linux/amd64
Python 3.11.9

![image (1)](https://github.com/user-attachments/assets/f3be780c-f611-4c84-b2cc-068320622a0e)
![image](https://github.com/user-attachments/assets/0fe1cca1-fa2d-46e9-9920-5086e60979e6)

**Comment by edoardottt** [comment]
It's really weird tbh. I have this python version `Python 3.12.3 (main) [GCC 13.2.0] on linux` and everything's fine.

**Comment by casportal** [comment]
Interesting I have gcc (Debian 13.3.0-3) 13.3.0 and Python 3.11.9 on kali linux. I wonder if it has something to do with linux distro and if i should try it on another.

**Comment by edoardottt** [comment]
All the input you try give you this error or only certain ones?

**Comment by casportal** [comment]
every variation of the takeover command I use gives me this error.

**Comment by GMDSantana** [comment]
The `PERCENT` function is returning a lambda instead of a calculated numeric value, which results in the formatting error. I sent a fix for this: #3.

> I found takeover finder v0.2 and have been playing around with it, however when I run the (python3 takeover.py -l domains.txt -v) or (python3 takeover.py -d google.com -v) command I get an error which I added below as well as the line 303 of code from the takeover.py file. I'm not sure why the string is invalid and if you have come across this problem before and have a solution. Any help would be greatly appreciated.
> 
> go version go1.22.5 linux/amd64 Python 3.11.9
> 
> ![image (1)](https://private-user-images.githubusercontent.com/177052489/354645071-f3be780c-f611-4c84-b2cc-068320622a0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MzIzNjIsIm5iZiI6MTczMDUzMjA2MiwicGF0aCI6Ii8xNzcwNTI0ODkvMzU0NjQ1MDcxLWYzYmU3ODBjLWY2MTEtNGM4NC1iMmNjLTA2ODMyMDYyMmEwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQwNzIxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YThlNzI1OWI0Nzc5Yzc1OGEwNDdmYWZmNzA3OGNiZjlhMWQzMTNkYzc1ZWYxYzAwYzdkNTcwZDMwNDA3ODg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eKHojiWZUXqwwJ0BX_x9-9-PK1U9z5eHVR5wtI5nP_E) ![image](https://private-user-images.githubusercontent.com/177052489/354645076-0fe1cca1-fa2d-46e9-9920-5086e60979e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1MzIzNjIsIm5iZiI6MTczMDUzMjA2MiwicGF0aCI6Ii8xNzcwNTI0ODkvMzU0NjQ1MDc2LTBmZTFjY2ExLWZhMmQtNDZlOS05OTIwLTUwODZlNjA5NzllNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQwNzIxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDM2NGRiYTFjN2JlZmRjMzVlMDRiMDQ4N2U3N2M0MWI4ZTRmNWYxNWYyZDZjNjZjMTFlZTVjMmI2N2NhODMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.33b30azx0s_bHaDp-JvA69jLnbrvITLFvg24ZlPWhNM)

**Comment by edoardottt** [comment]
thanks for your contribution!
